# Generated by Django 2.2.10 on 2020-02-24 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0269_gitlab_auth'),
    ]

    operations = [
        migrations.AddField(
            model_name='realm',
            name='enable_first_message',
            field=models.BooleanField(default=False),
        ),
    ]
