# Generated by Django 2.2.10 on 2020-02-24 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0270_realm_enable_first_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='realm',
            name='url_link',
            field=models.TextField(default='none'),
        ),
    ]
