# Generated by Django 2.2.10 on 2020-02-27 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0271_realm_url_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='display_welcome',
            field=models.BooleanField(default=False),
        ),
    ]
