# Generated by Django 2.2.10 on 2020-02-27 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0272_userprofile_display_welcome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='display_welcome',
            new_name='shown_org_banner',
        ),
    ]
